import { getThumbnail, getName, getDisplay, getAvailable, getEdit, getDelete, getWifi, getBathrooms, getBeds } from "./RoomTableColumnFunctions";
export default [
    {
      field: "thumbnail",
      headerName: "Thumbnail",
      width: 200,
      sortable: false,
      filterable: false,
      renderCell: getThumbnail,
    },
    {
      field: "name",
      headerName: "Name",
      width: 100,
      minWidth: 100,
      maxWidth: 200,
      sortable:true,
      valueGetter: getName,
    },
    {
      field: "display",
      headerName: "Display",
      width:100,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable:false,
      renderCell: getDisplay,
    },
    {
      field: "available",
      headerName: "Available",
      width:100,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable:false,
      renderCell: getAvailable,
    },
    {
      field: "beds",
      headerName: "Beds",
      width:100,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable:false,
      valueGetter: getBeds,
    },
    {
      field: "bathrooms",
      headerName: "Bathrooms",
      width:100,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable:false,
      valueGetter: getBathrooms,
    },
    {
      field: "wifi",
      headerName: "Wifi",
      width:100,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable:false,
      renderCell: getWifi,
    },
    {
      field: "edit",
      headerName: "Edit",
      width: 50,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable: false ,
      renderCell:getEdit,
    },
    {
      field: "delete",
      headerName:"Delete",
      width: 50,
      minWidth: 100,
      maxWidth: 150,
      sortable:false,
      filterable: false ,
      renderCell:getDelete
    },
  ];